### ISSUE TITLE
Small error in tutorial

### ISSUE THREAD

**Issue by dawulf** [clayford/DataWranglingInR#1]
Hi Clay, 
Thanks for your helpful data wrangling overviews. Just wanted to point out a small error in one of them, since it happens to be the first result on google when searching for things like "R data generation". At this line (and the 4 below it) you say you're drawing 100 samples of the sum of 2 dice rolls, but the sampling mechanism you use assumes every such sum is equally likely. That is, in the simulation the sum of the rolls is just as likely to be equal to 2 as it is to be equal to 7, even though that shouldn't be the case (and isn't in the lines before these).
https://github.com/clayford/DataWranglingInR/blob/65aa4292b0cf9747b110427ce4490813c2b395b8/dwr_10_generating_data.R#L70
Note that the result that shows up on google under a slightly different page (https://clayford.github.io/dwir/dwr_12_generating_data.html, which I couldn't find on your github) so changing these particular lines may not change the page that shows up.
I appreciate you taking a look.

**Comment by clayford** [comment]
Yikes. That's embarrassing. All credibility lost. Thanks for the heads up. I will fix as soon as I can.
